const products = [
 {
    "model": "iPhone 8 Pro",
    "price": 1300,
    "brand": "Apple",
    "os": "IOS",
    "color": "gold",
    "description": "iPhone 8 Pro - це професійна версія iPhone 8 з додатковими функціями та покращеними характеристиками.",
    "discount": 130,
    "imagePath": "img/iphone8pro.jpg",
    "reviews": 220,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "3000-3999 mAh",
    "fastCharging": "33 W",
    "frontCamera": "8 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Mp",
    "simCount": "2 SIM",
    "ram": "6 GB",
    "storage": "128 GB",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 3
  },
  {
    "model": "iPhone X",
    "price": 1400,
    "brand": "Apple",
    "os": "IOS",
    "color": "black",
    "description": "iPhone X - це революційний смартфон від Apple з безрамковим дизайном та Face ID.",
    "discount": 140,
    "imagePath": "img/iphonex.jpg",
    "reviews": 250,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "3000-3999 mAh",
    "fastCharging": "33 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "6 GB",
    "storage": "128 GB",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 3
  },
  {
    "model": "iPhone X Pro",
    "price": 1500,
    "brand": "Apple",
    "os": "IOS",
    "color": "gold",
    "description": "iPhone X Pro - це покращена версія iPhone X з додатковими функціями та продуктивністю.",
    "discount": 150,
    "imagePath": "img/iphonexpro.jpg",
    "reviews": 260,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "4000-4999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 3
  },
  {
    "model": "iPhone XR",
    "price": 1300,
    "brand": "Apple",
    "os": "IOS",
    "color": "black",
    "description": "iPhone XR - це доступна версія iPhone X з LCD дисплеєм та відмінною продуктивністю.",
    "discount": 130,
    "imagePath": "img/iphonexr.jpg",
    "reviews": 300,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "3000-3999 mAh",
    "fastCharging": "33 W",
    "frontCamera": "8 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Mp",
    "simCount": "2 SIM",
    "ram": "6 GB",
    "storage": "64 GB",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 3
  },
  {
    "model": "iPhone 11",
    "price": 1600,
    "brand": "Apple",
    "os": "IOS",
    "color": "black",
    "description": "iPhone 11 - це оновлена модель з подвійною камерою та новим процесором A13 Bionic.",
    "discount": 160,
    "imagePath": "img/iphone11.jpg",
    "reviews": 400,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "4000-4999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "iPhone 11 Pro",
    "price": 1800,
    "brand": "Apple",
    "os": "IOS",
    "color": "gold",
    "description": "iPhone 11 Pro - це професійна модель з потрійною камерою та покращеною продуктивністю.",
    "discount": 180,
    "imagePath": "img/iphone11pro.jpg",
    "reviews": 450,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "4000-4999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "iPhone 11 Pro Max",
    "price": 2000,
    "brand": "Apple",
    "os": "IOS",
    "color": "gold",
    "description": "iPhone 11 Pro Max - це найпотужніша версія iPhone 11 з великим дисплеєм та покращеною батареєю.",
    "discount": 200,
    "imagePath": "img/iphone11promax.jpg",
    "reviews": 500,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "5000-5999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "iPhone 12",
    "price": 1700,
    "brand": "Apple",
    "os": "IOS",
    "color": "black",
    "description": "iPhone 12 - це новий iPhone з підтримкою 5G та новим дизайном.",
    "discount": 170,
    "imagePath": "img/iphone12.jpg",
    "reviews": 550,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "4000-4999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "iPhone 12 Mini",
    "price": 1500,
    "brand": "Apple",
    "os": "IOS",
    "color": "black",
    "description": "iPhone 12 Mini - це компактна версія iPhone 12 з тими ж функціями в меншому корпусі.",
    "discount": 150,
    "imagePath": "img/iphone12mini.jpg",
    "reviews": 600,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "3000-3999 mAh",
    "fastCharging": "33 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Mp",
    "simCount": "2 SIM",
    "ram": "6 GB",
    "storage": "128 GB",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 3
  },
  {
    "model": "Meizu M1 Note",
    "price": 250,
    "brand": "Meizu",
    "os": "Android",
    "color": "blue",
    "description": "Meizu M1 Note - це доступний смартфон з хорошою камерою і яскравим дисплеєм.",
    "discount": 25,
    "imagePath": "img/meizuM1Note.jpg",
    "reviews": 1500,
    "simType": "Micro-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Plastic",
    "batteryCapacity": "3000-3999 mAh",
    "fastCharging": "No",
    "frontCamera": "5 Mp",
    "screenResolution": "HD+",
    "mainCamera": "48 Mp",
    "simCount": "2 SIM",
    "ram": "4 GB",
    "storage": "32 GB",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 2
  },
  {
    "model": "Meizu M2 Note",
    "price": 270,
    "brand": "Meizu",
    "os": "Android",
    "color": "white",
    "description": "Meizu M2 Note - це покращена версія M1 Note з оновленими характеристиками.",
    "discount": 27,
    "imagePath": "img/meizuM2Note.jpg",
    "reviews": 1600,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "3000-3999 mAh",
    "fastCharging": "No",
    "frontCamera": "8 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Mp",
    "simCount": "2 SIM",
    "ram": "4 GB",
    "storage": "64 GB",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 2
  },
  {
    "model": "Meizu M3 Note",
    "price": 300,
    "brand": "Meizu",
    "os": "Android",
    "color": "gray",
    "description": "Meizu M3 Note - це стильний смартфон з металевим корпусом і хорошою камерою.",
    "discount": 30,
    "imagePath": "img/meizuM3Note.jpg",
    "reviews": 1700,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "4000-4999 mAh",
    "fastCharging": "33 W",
    "frontCamera": "8 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Mp",
    "simCount": "2 SIM",
    "ram": "6 GB",
    "storage": "64 GB",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 3
  },
  {
    "model": "Meizu M5 Note",
    "price": 320,
    "brand": "Meizu",
    "os": "Android",
    "color": "black",
    "description": "Meizu M5 Note - це бюджетний смартфон з хорошою камерою і великим дисплеєм.",
    "discount": 32,
    "imagePath": "img/meizuM5Note.jpg",
    "reviews": 1800,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "4000-4999 mAh",
    "fastCharging": "33 W",
    "frontCamera": "8 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Mp",
    "simCount": "2 SIM",
    "ram": "6 GB",
    "storage": "128 GB",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 3
  },
  {
    "model": "Meizu M6 Note",
    "price": 350,
    "brand": "Meizu",
    "os": "Android",
    "color": "gold",
    "description": "Meizu M6 Note - це смартфон з подвійною камерою і великим акумулятором.",
    "discount": 35,
    "imagePath": "img/meizuM6Note.jpg",
    "reviews": 1900,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "5000-5999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "Meizu M3s",
    "price": 200,
    "brand": "Meizu",
    "os": "Android",
    "color": "silver",
    "description": "Meizu M3s - це компактний і доступний смартфон з хорошою камерою.",
    "discount": 20,
    "imagePath": "img/meizuM3s.jpg",
    "reviews": 2000,
    "simType": "Micro-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Plastic",
    "batteryCapacity": "3000-3999 mAh",
    "fastCharging": "No",
    "frontCamera": "5 Mp",
    "screenResolution": "HD+",
    "mainCamera": "48 Mp",
    "simCount": "1 SIM",
    "ram": "4 GB",
    "storage": "32 GB",
    "screenSize": "4\" - 4.99\"",
    "numberOfCameras": 2
  },
  {
    "model": "Meizu M5s",
    "price": 220,
    "brand": "Meizu",
    "os": "Android",
    "color": "black",
    "description": "Meizu M5s - це покращена версія M3s з більш потужним процесором.",
    "discount": 22,
    "imagePath": "img/meizuM5s.jpg",
    "reviews": 2100,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Plastic",
    "batteryCapacity": "3000-3999 mAh",
    "fastCharging": "No",
    "frontCamera": "8 Mp",
    "screenResolution": "HD+",
    "mainCamera": "48 Mp",
    "simCount": "2 SIM",
    "ram": "4 GB",
    "storage": "64 GB",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 2
  },
  {
    "model": "Meizu M6s",
    "price": 240,
    "brand": "Meizu",
    "os": "Android",
    "color": "blue",
    "description": "Meizu M6s - це смартфон з сучасним дизайном і хорошими характеристиками.",
    "discount": 24,
    "imagePath": "img/meizuM6s.jpg",
    "reviews": 2200,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "3000-3999 mAh",
    "fastCharging": "33 W",
    "frontCamera": "8 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Mp",
    "simCount": "2 SIM",
    "ram": "6 GB",
    "storage": "64 GB",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 3
  },
  {
    "model": "Meizu MX4",
    "price": 350,
    "brand": "Meizu",
    "os": "Android",
    "color": "gray",
    "description": "Meizu MX4 - це смартфон з чудовою камерою і високою продуктивністю.",
    "discount": 35,
    "imagePath": "img/meizuMX4.jpg",
    "reviews": 2300,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "4000-4999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "8 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Mp",
    "simCount": "2 SIM",
    "ram": "6 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 3
  },
  {
    "model": "Meizu MX5",
    "price": 400,
    "brand": "Meizu",
    "os": "Android",
    "color": "black",
    "description": "Meizu MX5 - це флагманський смартфон з металевим корпусом і відмінною камерою.",
    "discount": 40,
    "imagePath": "img/meizuMX5.jpg",
    "reviews": 2400,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "4000-4999 mAh",
    "fastCharging": "33 W",
    "frontCamera": "8 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Mp",
    "simCount": "2 SIM",
    "ram": "6 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 3
  },
  {
    "model": "Meizu Pro 5",
    "price": 500,
    "brand": "Meizu",
    "os": "Android",
    "color": "silver",
    "description": "Meizu Pro 5 - це преміальний смартфон з чудовою камерою і великим дисплеєм.",
    "discount": 50,
    "imagePath": "img/meizuPro5.jpg",
    "reviews": 2600,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "5000-5999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "Meizu Pro 6",
    "price": 550,
    "brand": "Meizu",
    "os": "Android",
    "color": "black",
    "description": "Meizu Pro 6 - це оновлена версія Pro 5 з більш потужним процесором.",
    "discount": 55,
    "imagePath": "img/meizuPro6.jpg",
    "reviews": 2700,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "5000-5999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "Meizu Pro 7",
    "price": 600,
    "brand": "Meizu",
    "os": "Android",
    "color": "blue",
    "description": "Meizu Pro 7 - це інноваційний смартфон з двома екранами і відмінною камерою.",
    "discount": 60,
    "imagePath": "img/meizuPro7.jpg",
    "reviews": 2800,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "5000-5999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "Meizu Pro 7 Plus",
    "price": 650,
    "brand": "Meizu",
    "os": "Android",
    "color": "gold",
    "description": "Meizu Pro 7 Plus - це версія Pro 7 з більшим дисплеєм і покращеними характеристиками.",
    "discount": 65,
    "imagePath": "img/meizuPro7Plus.jpg",
    "reviews": 2900,
    "simType": "Nano-SIM",
    "videoResolution": "8K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "5000-5999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "Meizu 16th",
    "price": 700,
    "brand": "Meizu",
    "os": "Android",
    "color": "black",
    "description": "Meizu 16th - це флагманський смартфон з тонкими рамками і високою продуктивністю.",
    "discount": 70,
    "imagePath": "img/meizu16th.jpg",
    "reviews": 3000,
    "simType": "Nano-SIM",
    "videoResolution": "8K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "5000-5999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "Meizu 16th Plus",
    "price": 750,
    "brand": "Meizu",
    "os": "Android",
    "color": "blue",
    "description": "Meizu 16th Plus - це версія 16th з більшим екраном і потужним процесором.",
    "discount": 75,
    "imagePath": "img/meizu16thPlus.jpg",
    "reviews": 3100,
    "simType": "Nano-SIM",
    "videoResolution": "8K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "5000-5999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
   {
    "model": "Motorola Moto G4",
    "price": 200,
    "brand": "Motorola",
    "os": "Android",
    "color": "black",
    "description": "Motorola Moto G4 - це доступний смартфон з хорошим екраном і камерою.",
    "discount": 20,
    "imagePath": "img/motorolaMotoG4.jpg",
    "reviews": 1500,
    "simType": "Micro-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Plastic",
    "batteryCapacity": "3000-3999 mAh",
    "fastCharging": "No",
    "frontCamera": "5 Mp",
    "screenResolution": "HD+",
    "mainCamera": "48 Mp",
    "simCount": "2 SIM",
    "ram": "4 GB",
    "storage": "32 GB",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 2
  },
  {
    "model": "Motorola Moto G5",
    "price": 250,
    "brand": "Motorola",
    "os": "Android",
    "color": "gray",
    "description": "Motorola Moto G5 - це оновлена версія Moto G4 з покращеною продуктивністю.",
    "discount": 25,
    "imagePath": "img/motorolaMotoG5.jpg",
    "reviews": 1600,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "3000-3999 mAh",
    "fastCharging": "No",
    "frontCamera": "8 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Mp",
    "simCount": "2 SIM",
    "ram": "4 GB",
    "storage": "64 GB",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 2
  },
  {
    "model": "Motorola Moto G6",
    "price": 300,
    "brand": "Motorola",
    "os": "Android",
    "color": "white",
    "description": "Motorola Moto G6 - це смартфон середнього класу з хорошим екраном і камерою.",
    "discount": 30,
    "imagePath": "img/motorolaMotoG6.jpg",
    "reviews": 1700,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "3000-3999 mAh",
    "fastCharging": "No",
    "frontCamera": "8 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Mp",
    "simCount": "2 SIM",
    "ram": "6 GB",
    "storage": "64 GB",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 3
  },
  {
    "model": "Motorola Moto G7",
    "price": 350,
    "brand": "Motorola",
    "os": "Android",
    "color": "black",
    "description": "Motorola Moto G7 - це смартфон з великим дисплеєм і хорошою продуктивністю.",
    "discount": 35,
    "imagePath": "img/motorolaMotoG7.jpg",
    "reviews": 1800,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "4000-4999 mAh",
    "fastCharging": "33 W",
    "frontCamera": "8 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Mp",
    "simCount": "2 SIM",
    "ram": "6 GB",
    "storage": "128 GB",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 3
  },
  {
    "model": "Motorola Moto G8",
    "price": 400,
    "brand": "Motorola",
    "os": "Android",
    "color": "blue",
    "description": "Motorola Moto G8 - це оновлений смартфон з покращеними характеристиками і камерою.",
    "discount": 40,
    "imagePath": "img/motorolaMotoG8.jpg",
    "reviews": 1900,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "4000-4999 mAh",
    "fastCharging": "33 W",
    "frontCamera": "8 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Mp",
    "simCount": "2 SIM",
    "ram": "6 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 3
  },
  {
    "model": "Motorola Moto G9",
    "price": 450,
    "brand": "Motorola",
    "os": "Android",
    "color": "gray",
    "description": "Motorola Moto G9 - це смартфон з чудовою батареєю і хорошою продуктивністю.",
    "discount": 45,
    "imagePath": "img/motorolaMotoG9.jpg",
    "reviews": 2000,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "5000-5999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "Motorola Moto G9 Plus",
    "price": 500,
    "brand": "Motorola",
    "os": "Android",
    "color": "gold",
    "description": "Motorola Moto G9 Plus - це версія G9 з великим екраном і покращеною камерою.",
    "discount": 50,
    "imagePath": "img/motorolaMotoG9Plus.jpg",
    "reviews": 2100,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "5000-5999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "Motorola Moto G10",
    "price": 550,
    "brand": "Motorola",
    "os": "Android",
    "color": "black",
    "description": "Motorola Moto G10 - це смартфон середнього класу з великим екраном і потужним акумулятором.",
    "discount": 55,
    "imagePath": "img/motorolaMotoG10.jpg",
    "reviews": 2200,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "5000-5999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "Motorola Moto G30",
    "price": 600,
    "brand": "Motorola",
    "os": "Android",
    "color": "blue",
    "description": "Motorola Moto G30 - це новий смартфон середнього класу з підтримкою 5G.",
    "discount": 60,
    "imagePath": "img/motorolaMotoG30.jpg",
    "reviews": 2300,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Metal",
    "batteryCapacity": "5000-5999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "Motorola Moto G60",
    "price": 650,
    "brand": "Motorola",
    "os": "Android",
    "color": "gold",
    "description": "Motorola Moto G60 - це смартфон з потужною камерою і великим дисплеєм.",
    "discount": 65,
    "imagePath": "img/motorolaMotoG60.jpg",
    "reviews": 2400,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "5000-5999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "Samsung Galaxy S7",
    "price": 500,
    "description": "Samsung Galaxy S7 — це стильний смартфон з чудовою камерою та продуктивністю.",
    "discount": 50,
    "imagePath": "img/samsungS7.jpg",
    "reviews": 1200,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Метал",
    "batteryCapacity": "3000-3999 мАг",
    "fastCharging": "Ні",
    "frontCamera": "5 Мп",
    "screenResolution": "HD+",
    "mainCamera": "12 Мп",
    "simCount": "1 SIM",
    "ram": "4 ГБ",
    "storage": "32 ГБ",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 2,
    "brand": "Samsung"
},
{
    "model": "Samsung Galaxy S7 Edge",
    "price": 550,
    "description": "Samsung Galaxy S7 Edge — це покращена версія Galaxy S7 із вигнутим екраном.",
    "discount": 55,
    "imagePath": "img/samsungS7Edge.jpg",
    "reviews": 1300,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Метал",
    "batteryCapacity": "3000-3999 мАг",
    "fastCharging": "Ні",
    "frontCamera": "5 Мп",
    "screenResolution": "HD+",
    "mainCamera": "12 Мп",
    "simCount": "1 SIM",
    "ram": "4 ГБ",
    "storage": "32 ГБ",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 2,
    "brand": "Samsung"
},
{
    "model": "Samsung Galaxy S8",
    "price": 600,
    "description": "Samsung Galaxy S8 — це новий флагман із безрамковим дизайном та потужним процесором.",
    "discount": 60,
    "imagePath": "img/samsungS8.jpg",
    "reviews": 1500,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Метал",
    "batteryCapacity": "3000-3999 мАг",
    "fastCharging": "33 Вт",
    "frontCamera": "8 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "12 Мп",
    "simCount": "2 SIM",
    "ram": "6 ГБ",
    "storage": "64 ГБ",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 2,
    "brand": "Samsung"
},
{
    "model": "Samsung Galaxy S8 Plus",
    "price": 650,
    "description": "Samsung Galaxy S8 Plus — це покращена версія S8 з більшим екраном.",
    "discount": 65,
    "imagePath": "img/samsungS8Plus.jpg",
    "reviews": 1600,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Метал",
    "batteryCapacity": "4000-4999 мАг",
    "fastCharging": "33 Вт",
    "frontCamera": "8 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "12 Мп",
    "simCount": "2 SIM",
    "ram": "6 ГБ",
    "storage": "64 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 2,
    "brand": "Samsung"
},
{
    "model": "Samsung Galaxy S9",
    "price": 700,
    "description": "Samsung Galaxy S9 — це флагман зі покращеною камерою та підтримкою AR.",
    "discount": 70,
    "imagePath": "img/samsungS9.jpg",
    "reviews": 1800,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Метал",
    "batteryCapacity": "3000-3999 мАг",
    "fastCharging": "33 Вт",
    "frontCamera": "8 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "12 Мп",
    "simCount": "2 SIM",
    "ram": "6 ГБ",
    "storage": "64 ГБ",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 3,
    "brand": "Samsung"
},
{
    "model": "Samsung Galaxy S9 Plus",
    "price": 750,
    "description": "Samsung Galaxy S9 Plus — це версія S9 із більшим дисплеєм та покращеною камерою.",
    "discount": 75,
    "imagePath": "img/samsungS9Plus.jpg",
    "reviews": 1900,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Метал",
    "batteryCapacity": "4000-4999 мАг",
    "fastCharging": "33 Вт",
    "frontCamera": "8 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "12 Мп",
    "simCount": "2 SIM",
    "ram": "6 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 3,
    "brand": "Samsung"
},
{
    "model": "Samsung Galaxy Note 8",
    "price": 800,
    "description": "Samsung Galaxy Note 8 — це смартфон із великим екраном і підтримкою стилуса S-Pen.",
    "discount": 80,
    "imagePath": "img/samsungNote8.jpg",
    "reviews": 2000,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Метал",
    "batteryCapacity": "4000-4999 мАг",
    "fastCharging": "33 Вт",
    "frontCamera": "8 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "12 Мп",
    "simCount": "2 SIM",
    "ram": "6 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 3,
    "brand": "Samsung"
},
{
    "model": "Samsung Galaxy Note 9",
    "price": 850,
    "description": "Samsung Galaxy Note 9 — це флагманський смартфон із підтримкою стилуса і потужним акумулятором.",
    "discount": 85,
    "imagePath": "img/samsungNote9.jpg",
    "reviews": 2200,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Метал",
    "batteryCapacity": "4000-4999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "8 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "12 Мп",
    "simCount": "2 SIM",
    "ram": "6 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 3,
    "brand": "Samsung"
},
{
    "model": "Samsung Galaxy S10",
    "price": 900,
    "description": "Samsung Galaxy S10 — це смартфон із потрійною камерою та відмінною продуктивністю.",
    "discount": 90,
    "imagePath": "img/samsungS10.jpg",
    "reviews": 2400,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "4000-4999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "10 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Мп",
    "simCount": "2 SIM",
    "ram": "8 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 3,
    "brand": "Samsung"
},
{
    "model": "Samsung Galaxy S10 Plus",
    "price": 950,
    "description": "Samsung Galaxy S10 Plus — це версія S10 з більшим екраном та збільшеним акумулятором.",
    "discount": 95,
    "imagePath": "img/samsungS10Plus.jpg",
    "reviews": 2500,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "5000-5999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "10 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Мп",
    "simCount": "2 SIM",
    "ram": "8 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung",
},
  {
    "model": "Samsung Galaxy Note 10",
    "price": 1000,
    "description": "Samsung Galaxy Note 10 — це флагман із підтримкою стилуса та новим дизайном.",
    "discount": 100,
    "imagePath": "img/samsungNote10.jpg",
    "reviews": 2700,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "4000-4999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "10 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Мп",
    "simCount": "2 SIM",
    "ram": "8 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy Note 10 Plus",
    "price": 1050,
    "description": "Samsung Galaxy Note 10 Plus — це покращена версія Note 10 із більшим екраном.",
    "discount": 105,
    "imagePath": "img/samsungNote10Plus.jpg",
    "reviews": 2800,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "5000-5999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "10 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Мп",
    "simCount": "2 SIM",
    "ram": "8 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy S20",
    "price": 1100,
    "description": "Samsung Galaxy S20 — це новий флагман із підтримкою 5G та покращеною камерою.",
    "discount": 110,
    "imagePath": "img/samsungS20.jpg",
    "reviews": 3000,
    "simType": "Nano-SIM",
    "videoResolution": "8K UHD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "5000-5999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "15 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Мп",
    "simCount": "2 SIM",
    "ram": "8 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy S20 Plus",
    "price": 1150,
    "description": "Samsung Galaxy S20 Plus — це версія S20 з більшим екраном та покращеною камерою.",
    "discount": 115,
    "imagePath": "img/samsungS20Plus.jpg",
    "reviews": 3100,
    "simType": "Nano-SIM",
    "videoResolution": "8K UHD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "5000-5999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "15 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Мп",
    "simCount": "2 SIM",
    "ram": "8 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy S20 Ultra",
    "price": 1200,
    "description": "Samsung Galaxy S20 Ultra — це найпотужніша версія S20 з інноваційною камерою.",
    "discount": 120,
    "imagePath": "img/samsungS20Ultra.jpg",
    "reviews": 3200,
    "simType": "Nano-SIM",
    "videoResolution": "8K UHD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "5000-5999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "15 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Мп",
    "simCount": "2 SIM",
    "ram": "8 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy Note 20",
    "price": 1250,
    "description": "Samsung Galaxy Note 20 — це флагман із підтримкою стилуса і відмінним дисплеєм.",
    "discount": 125,
    "imagePath": "img/samsungNote20.jpg",
    "reviews": 3300,
    "simType": "Nano-SIM",
    "videoResolution": "8K UHD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "5000-5999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "15 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Мп",
    "simCount": "2 SIM",
    "ram": "8 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy Note 20 Ultra",
    "price": 1300,
    "description": "Samsung Galaxy Note 20 Ultra — це версія Note 20 з більшим дисплеєм та покращеними характеристиками.",
    "discount": 130,
    "imagePath": "img/samsungNote20Ultra.jpg",
    "reviews": 3400,
    "simType": "Nano-SIM",
    "videoResolution": "8K UHD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "5000-5999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "15 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Мп",
    "simCount": "2 SIM",
    "ram": "8 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy S21",
    "price": 1350,
    "description": "Samsung Galaxy S21 — це новий флагман із підтримкою 5G і покращеною камерою.",
    "discount": 135,
    "imagePath": "img/samsungS21.jpg",
    "reviews": 3500,
    "simType": "Nano-SIM",
    "videoResolution": "8K UHD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "5000-5999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "15 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Мп",
    "simCount": "2 SIM",
    "ram": "8 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy S21 Plus",
    "price": 1400,
    "description": "Samsung Galaxy S21 Plus — це версія S21 з більшим дисплеєм і збільшеною батареєю.",
    "discount": 140,
    "imagePath": "img/samsungS21Plus.jpg",
    "reviews": 3600,
    "simType": "Nano-SIM",
    "videoResolution": "8K UHD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "5000-5999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "15 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Мп",
    "simCount": "2 SIM",
    "ram": "8 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy S21 Ultra",
    "price": 1450,
    "description": "Samsung Galaxy S21 Ultra — це найпотужніша версія S21 з інноваційною камерою.",
    "discount": 145,
    "imagePath": "img/samsungS21Ultra.jpg",
    "reviews": 3700,
    "simType": "Nano-SIM",
    "videoResolution": "8K UHD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "5000-5999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "15 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Мп",
    "simCount": "2 SIM",
    "ram": "8 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
 {
    "model": "Samsung Galaxy A51",
    "price": 400,
    "description": "Samsung Galaxy A51 — це доступний смартфон з чудовою камерою та стильним дизайном.",
    "discount": 40,
    "imagePath": "img/samsungA51.jpg",
    "reviews": 3800,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "4000-4999 мАг",
    "fastCharging": "33 Вт",
    "frontCamera": "8 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Мп",
    "simCount": "2 SIM",
    "ram": "6 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy A71",
    "price": 450,
    "description": "Samsung Galaxy A71 — це смартфон середнього класу з чудовою продуктивністю та камерою.",
    "discount": 45,
    "imagePath": "img/samsungA71.jpg",
    "reviews": 3900,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "4000-4999 мАг",
    "fastCharging": "33 Вт",
    "frontCamera": "8 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Мп",
    "simCount": "2 SIM",
    "ram": "6 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy A32",
    "price": 300,
    "description": "Samsung Galaxy A32 — це бюджетний смартфон із гарною камерою та великим екраном.",
    "discount": 30,
    "imagePath": "img/samsungA32.jpg",
    "reviews": 4000,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "4000-4999 мАг",
    "fastCharging": "33 Вт",
    "frontCamera": "8 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Мп",
    "simCount": "2 SIM",
    "ram": "4 ГБ",
    "storage": "64 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 3,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy A52",
    "price": 500,
    "description": "Samsung Galaxy A52 — це доступний смартфон із чудовим екраном та камерою.",
    "discount": 50,
    "imagePath": "img/samsungA52.jpg",
    "reviews": 4100,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "4000-4999 мАг",
    "fastCharging": "33 Вт",
    "frontCamera": "8 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Мп",
    "simCount": "2 SIM",
    "ram": "6 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy Z Fold 2",
    "price": 2000,
    "description": "Samsung Galaxy Z Fold 2 — це флагманський смартфон із гнучким екраном та підтримкою 5G.",
    "discount": 200,
    "imagePath": "img/samsungZFold2.jpg",
    "reviews": 4200,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "5000-5999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "15 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Мп",
    "simCount": "2 SIM",
    "ram": "8 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy Z Flip",
    "price": 1500,
    "description": "Samsung Galaxy Z Flip — це стильний смартфон із гнучким екраном та компактним дизайном.",
    "discount": 150,
    "imagePath": "img/samsungZFlip.jpg",
    "reviews": 4300,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "4000-4999 мАг",
    "fastCharging": "33 Вт",
    "frontCamera": "8 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Мп",
    "simCount": "2 SIM",
    "ram": "6 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy M31",
    "price": 350,
    "description": "Samsung Galaxy M31 — це бюджетний смартфон з великою батареєю та чудовою камерою.",
    "discount": 35,
    "imagePath": "img/samsungM31.jpg",
    "reviews": 4400,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "5000-5999 мАг",
    "fastCharging": "33 Вт",
    "frontCamera": "8 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Мп",
    "simCount": "2 SIM",
    "ram": "4 ГБ",
    "storage": "64 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 3,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy M51",
    "price": 450,
    "description": "Samsung Galaxy M51 — це смартфон середнього класу з потужною батареєю та чудовою камерою.",
    "discount": 45,
    "imagePath": "img/samsungM51.jpg",
    "reviews": 4500,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "5000-5999 мАг",
    "fastCharging": "33 Вт",
    "frontCamera": "8 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Мп",
    "simCount": "2 SIM",
    "ram": "6 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy F41",
    "price": 300,
    "description": "Samsung Galaxy F41 — це бюджетний смартфон із гарною камерою та великим екраном.",
    "discount": 30,
    "imagePath": "img/samsungF41.jpg",
    "reviews": 4600,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "4000-4999 мАг",
    "fastCharging": "33 Вт",
    "frontCamera": "8 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Мп",
    "simCount": "2 SIM",
    "ram": "4 ГБ",
    "storage": "64 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 3,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy F62",
    "price": 400,
    "description": "Samsung Galaxy F62 — це смартфон із чудовою камерою та великою батареєю.",
    "discount": 40,
    "imagePath": "img/samsungF62.jpg",
    "reviews": 4700,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "5000-5999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "8 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Мп",
    "simCount": "2 SIM",
    "ram": "6 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy S22",
    "price": 1550,
    "description": "Samsung Galaxy S22 — це новий флагман від Samsung із підтримкою 5G та покращеною камерою.",
    "discount": 155,
    "imagePath": "img/samsungS22.jpg",
    "reviews": 4800,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "4000-4999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "15 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Мп",
    "simCount": "2 SIM",
    "ram": "8 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy S22 Plus",
    "price": 1600,
    "description": "Samsung Galaxy S22 Plus — це версія S22 з більшим дисплеєм та покращеною батареєю.",
    "discount": 160,
    "imagePath": "img/samsungS22Plus.jpg",
    "reviews": 4900,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "5000-5999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "15 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Мп",
    "simCount": "2 SIM",
    "ram": "8 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy S22 Ultra",
    "price": 1650,
    "description": "Samsung Galaxy S22 Ultra — це найпотужніша версія S22 з інноваційною камерою та підтримкою стилуса.",
    "discount": 165,
    "imagePath": "img/samsungS22Ultra.jpg",
    "reviews": 5000,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "5000-5999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "15 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Мп",
    "simCount": "2 SIM",
    "ram": "8 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy Z Fold 3",
    "price": 2100,
    "description": "Samsung Galaxy Z Fold 3 — це інноваційний смартфон із гнучким екраном та підтримкою 5G.",
    "discount": 210,
    "imagePath": "img/samsungZFold3.jpg",
    "reviews": 5100,
    "simType": "Nano-SIM",
    "videoResolution": "8K UHD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "5000-5999 мАг",
    "fastCharging": "45 Вт",
    "frontCamera": "15 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Мп",
    "simCount": "2 SIM",
    "ram": "8 ГБ",
    "storage": "256 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy Z Flip 3",
    "price": 1600,
    "description": "Samsung Galaxy Z Flip 3 — це стильний смартфон із гнучким екраном і компактним дизайном.",
    "discount": 160,
    "imagePath": "img/samsungZFlip3.jpg",
    "reviews": 5200,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Скло",
    "batteryCapacity": "4000-4999 мАг",
    "fastCharging": "33 Вт",
    "frontCamera": "8 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Мп",
    "simCount": "2 SIM",
    "ram": "6 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 3,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy A12",
    "price": 250,
    "description": "Samsung Galaxy A12 — це доступний смартфон із гарною камерою та великим екраном.",
    "discount": 25,
    "imagePath": "img/samsungA12.jpg",
    "reviews": 5300,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Пластик",
    "batteryCapacity": "4000-4999 мАг",
    "fastCharging": "Немає",
    "frontCamera": "5 Мп",
    "screenResolution": "HD+",
    "mainCamera": "48 Мп",
    "simCount": "1 SIM",
    "ram": "4 ГБ",
    "storage": "64 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 3,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy A02",
    "price": 200,
    "description": "Samsung Galaxy A02 — це бюджетний смартфон із основними функціями та гарною камерою.",
    "discount": 20,
    "imagePath": "img/samsungA02.jpg",
    "reviews": 5400,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Пластик",
    "batteryCapacity": "4000-4999 мАг",
    "fastCharging": "Немає",
    "frontCamera": "5 Мп",
    "screenResolution": "HD+",
    "mainCamera": "48 Мп",
    "simCount": "1 SIM",
    "ram": "4 ГБ",
    "storage": "32 ГБ",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 2,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy M12",
    "price": 300,
    "description": "Samsung Galaxy M12 — це бюджетний смартфон із гарною камерою та великим екраном.",
    "discount": 30,
    "imagePath": "img/samsungM12.jpg",
    "reviews": 5500,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Пластик",
    "batteryCapacity": "4000-4999 мАг",
    "fastCharging": "Немає",
    "frontCamera": "5 Мп",
    "screenResolution": "HD+",
    "mainCamera": "48 Мп",
    "simCount": "2 SIM",
    "ram": "4 ГБ",
    "storage": "64 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 3,
    "brand": "Samsung"
  },
  {
    "model": "Samsung Galaxy A32 5G",
    "price": 350,
    "description": "Samsung Galaxy A32 5G — це доступний смартфон із підтримкою 5G та гарною камерою.",
    "discount": 35,
    "imagePath": "img/samsungA32_5G.jpg",
    "reviews": 5600,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Пластик",
    "batteryCapacity": "4000-4999 мАг",
    "fastCharging": "Немає",
    "frontCamera": "8 Мп",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Мп",
    "simCount": "2 SIM",
    "ram": "6 ГБ",
    "storage": "128 ГБ",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4,
    "brand": "Samsung"
  },
  {
    "model": "Xiaomi Mi 6",
    "price": 400,
    "brand": "Xiaomi",
    "description": "Xiaomi Mi 6 - це стильний смартфон з чудовою продуктивністю і камерою.",
    "discount": 40,
    "imagePath": "img/xiaomiMi6.jpg",
    "reviews": 2100,
    "simType": "Nano-SIM",
    "videoResolution": "Full HD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "3000-3999 mAh",
    "fastCharging": "33 W",
    "frontCamera": "8 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Mp",
    "simCount": "2 SIM",
    "ram": "6 GB",
    "storage": "128 GB",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 3
  },
  {
    "model": "Xiaomi Mi 8",
    "price": 500,
    "brand": "Xiaomi",
    "description": "Xiaomi Mi 8 - це флагманський смартфон з подвійною камерою і потужним процесором.",
    "discount": 50,
    "imagePath": "img/xiaomiMi8.jpg",
    "reviews": 2300,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "4000-4999 mAh",
    "fastCharging": "33 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Mp",
    "simCount": "2 SIM",
    "ram": "6 GB",
    "storage": "128 GB",
    "screenSize": "5\" - 5.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "Xiaomi Mi 9",
    "price": 600,
    "brand": "Xiaomi",
    "description": "Xiaomi Mi 9 - це смартфон з потрійною камерою і чудовим дисплеєм.",
    "discount": 60,
    "imagePath": "img/xiaomiMi9.jpg",
    "reviews": 2500,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "4000-4999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "Xiaomi Mi 9T",
    "price": 550,
    "brand": "Xiaomi",
    "description": "Xiaomi Mi 9T - це смартфон середнього класу з гарною камерою і потужним процесором.",
    "discount": 55,
    "imagePath": "img/xiaomiMi9T.jpg",
    "reviews": 2400,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "4000-4999 mAh",
    "fastCharging": "33 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "48 Mp",
    "simCount": "2 SIM",
    "ram": "6 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 3
  },
  {
    "model": "Xiaomi Mi 9T Pro",
    "price": 650,
    "brand": "Xiaomi",
    "description": "Xiaomi Mi 9T Pro - це покращена версія Mi 9T з потужнішим процесором.",
    "discount": 65,
    "imagePath": "img/xiaomiMi9TPro.jpg",
    "reviews": 2600,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "4000-4999 mAh",
    "fastCharging": "33 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "Xiaomi Mi 10",
    "price": 700,
    "brand": "Xiaomi",
    "description": "Xiaomi Mi 10 - це флагман з підтримкою 5G і чудовою камерою.",
    "discount": 70,
    "imagePath": "img/xiaomiMi10.jpg",
    "reviews": 2800,
    "simType": "Nano-SIM",
    "videoResolution": "8K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "5000-5999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "Xiaomi Mi 10 Pro",
    "price": 800,
    "brand": "Xiaomi",
    "description": "Xiaomi Mi 10 Pro - це професійна версія Mi 10 з покращеною камерою.",
    "discount": 80,
    "imagePath": "img/xiaomiMi10Pro.jpg",
    "reviews": 2900,
    "simType": "Nano-SIM",
    "videoResolution": "8K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "5000-5999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "200 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "Xiaomi Mi 10T",
    "price": 750,
    "brand": "Xiaomi",
    "description": "Xiaomi Mi 10T - це смартфон середнього класу з чудовою камерою і продуктивністю.",
    "discount": 75,
    "imagePath": "img/xiaomiMi10T.jpg",
    "reviews": 2700,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "5000-5999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Mp",
    "simCount": "2 SIM",
    "ram": "6 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "Xiaomi Mi 10T Pro",
    "price": 850,
    "brand": "Xiaomi",
    "description": "Xiaomi Mi 10T Pro - це покращена версія Mi 10T з потужнішою камерою.",
    "discount": 85,
    "imagePath": "img/xiaomiMi10TPro.jpg",
    "reviews": 3000,
    "simType": "Nano-SIM",
    "videoResolution": "4K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "5000-5999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  },
  {
    "model": "Xiaomi Mi 11",
    "price": 900,
    "brand": "Xiaomi",
    "description": "Xiaomi Mi 11 - це новий флагман з чудовим дисплеєм і камерою.",
    "discount": 90,
    "imagePath": "img/xiaomiMi11.jpg",
    "reviews": 3100,
    "simType": "Nano-SIM",
    "videoResolution": "8K UHD",
    "bodyMaterial": "Glass",
    "batteryCapacity": "5000-5999 mAh",
    "fastCharging": "45 W",
    "frontCamera": "15 Mp",
    "screenResolution": "Full HD+",
    "mainCamera": "108 Mp",
    "simCount": "2 SIM",
    "ram": "8 GB",
    "storage": "128 GB",
    "screenSize": "6\" - 6.99\"",
    "numberOfCameras": 4
  }
]
module.exports = products;
