const products = [
 {
        "model": "iPhone 8 Pro",
        "price": 1300,
        "brand": "Apple",
        "os": "IOS",
        "color": "gold",
        "description": "iPhone 8 Pro - це професійна версія iPhone 8 з додатковими функціями та покращеними характеристиками.",
        "discount": 130,
        "imagePath": "img/iphone8pro.jpg",
        "reviews": 220
      },
      {
        "model": "iPhone X",
        "price": 1400,
        "brand": "Apple",
        "os": "IOS",
        "color": "black",
        "description": "iPhone X - це революційний смартфон від Apple з безрамковим дизайном та Face ID.",
        "discount": 140,
        "imagePath": "img/iphonex.jpg",
        "reviews": 250
      },
      {
        "model": "iPhone X Pro",
        "price": 1500,
        "brand": "Apple",
        "os": "IOS",
        "color": "gold",
        "description": "iPhone X Pro - це покращена версія iPhone X з додатковими функціями та продуктивністю.",
        "discount": 150,
        "imagePath": "img/iphonexpro.jpg",
        "reviews": 260
      },
      {
        "model": "iPhone XR",
        "price": 1300,
        "brand": "Apple",
        "os": "IOS",
        "color": "black",
        "description": "iPhone XR - це доступна версія iPhone X з LCD дисплеєм та відмінною продуктивністю.",
        "discount": 130,
        "imagePath": "img/iphonexr.jpg",
        "reviews": 300
      },
      {
        "model": "iPhone 11",
        "price": 1600,
        "brand": "Apple",
        "os": "IOS",
        "color": "black",
        "description": "iPhone 11 - це оновлена модель з подвійною камерою та новим процесором A13 Bionic.",
        "discount": 160,
        "imagePath": "img/iphone11.jpg",
        "reviews": 400
      },
      {
        "model": "iPhone 11 Pro",
        "price": 1800,
        "brand": "Apple",
        "os": "IOS",
        "color": "gold",
        "description": "iPhone 11 Pro - це професійна модель з потрійною камерою та покращеною продуктивністю.",
        "discount": 180,
        "imagePath": "img/iphone11pro.jpg",
        "reviews": 450
      },
      {
        "model": "iPhone 11 Pro Max",
        "price": 2000,
        "brand": "Apple",
        "os": "IOS",
        "color": "gold",
        "description": "iPhone 11 Pro Max - це найпотужніша версія iPhone 11 з великим дисплеєм та покращеною батареєю.",
        "discount": 200,
        "imagePath": "img/iphone11promax.jpg",
        "reviews": 500
      },
      {
        "model": "iPhone 12",
        "price": 1700,
        "brand": "Apple",
        "os": "IOS",
        "color": "black",
        "description": "iPhone 12 - це новий iPhone з підтримкою 5G та новим дизайном.",
        "discount": 170,
        "imagePath": "img/iphone12.jpg",
        "reviews": 550
      },
      {
        "model": "iPhone 12 Mini",
        "price": 1500,
        "brand": "Apple",
        "os": "IOS",
        "color": "black",
        "description": "iPhone 12 Mini - це компактна версія iPhone 12 з тими ж функціями в меншому корпусі.",
        "discount": 150,
        "imagePath": "img/iphone12mini.jpg",
        "reviews": 600
      },
      {
        "model": "iPhone 12 Pro",
        "price": 1900,
        "brand": "Apple",
        "os": "IOS",
        "color": "gold",
        "description": "iPhone 12 Pro - це професійна версія iPhone 12 з покращеною камерою та LiDAR сканером.",
        "discount": 190,
        "imagePath": "img/iphone12pro.jpg",
        "reviews": 650
      },
      {
        "model": "iPhone 12 Pro Max",
        "price": 2100,
        "brand": "Apple",
        "os": "IOS",
        "color": "gold",
        "description": "iPhone 12 Pro Max - це найпотужніша версія iPhone 12 з великим дисплеєм та покращеною камерою.",
        "discount": 210,
        "imagePath": "img/iphone12promax.jpg",
        "reviews": 700
      },
      {
        "model": "iPhone 13",
        "price": 1800,
        "brand": "Apple",
        "os": "IOS",
        "color": "black",
        "description": "iPhone 13 - це нова модель телефону від Apple з передовими технологіями та функціями.",
        "discount": 180,
        "imagePath": "img/iphone13.jpg",
        "reviews": 138
      },
      {
        "model": "iPhone 13 Mini",
        "price": 1600,
        "brand": "Apple",
        "os": "IOS",
        "color": "black",
        "description": "iPhone 13 Mini - це компактна версія iPhone 13 з тими ж функціями в меншому корпусі.",
        "discount": 160,
        "imagePath": "img/iphone13mini.jpg",
        "reviews": 150
      },
      {
        "model": "iPhone 13 Pro Max",
        "price": 2300,
        "brand": "Apple",
        "os": "IOS",
        "color": "gold",
        "description": "iPhone 13 Pro Max - це найпотужніша версія iPhone 13 з великим дисплеєм та покращеною камерою.",
        "discount": 230,
        "imagePath": "img/iphone13promax.jpg",
        "reviews": 250
      },
      {
        "model": "iPhone 14",
        "price": 1900,
        "brand": "Apple",
        "os": "IOS",
        "color": "black",
        "description": "iPhone 14 - це нова модель з покращеною продуктивністю та додатковими функціями.",
        "discount": 190,
        "imagePath": "img/iphone14.jpg",
        "reviews": 300
      },
      {
        "model": "iPhone 14 Pro",
        "price": 2200,
        "brand": "Apple",
        "os": "IOS",
        "color": "gold",
        "description": "iPhone 14 Pro - це професійна версія iPhone 14 з покращеною камерою та новими функціями.",
        "discount": 220,
        "imagePath": "img/iphone14pro.jpg",
        "reviews": 350
      },
      {
        "model": "iPhone 14 Pro Max",
        "price": 2400,
        "brand": "Apple",
        "os": "IOS",
        "color": "gold",
        "description": "iPhone 14 Pro Max - це найпотужніша версія iPhone 14 з великим дисплеєм та покращеною батареєю.",
        "discount": 240,
        "imagePath": "img/iphone14promax.jpg",
        "reviews": 400
      },
      {
        "model": "iPhone 15",
        "price": 2000,
        "brand": "Apple",
        "os": "IOS",
        "color": "black",
        "description": "iPhone 15 - це нова модель з покращеними характеристиками та передовими технологіями.",
        "discount": 200,
        "imagePath": "img/iphone15.jpg",
        "reviews": 500
      },
      {
        "model": "iPhone 15 Pro",
        "price": 2300,
        "brand": "Apple",
        "os": "IOS",
        "color": "gold",
        "description": "iPhone 15 Pro - це професійна версія iPhone 15 з покращеною продуктивністю та новими функціями.",
        "discount": 230,
        "imagePath": "img/iphone15pro.jpg",
        "reviews": 550
      },
      {
        "model": "iPhone 15 Pro Max",
        "price": 2500,
        "brand": "Apple",
        "os": "IOS",
        "color": "gold",
        "description": "iPhone 15 Pro Max - це найпотужніша версія iPhone 15 з великим дисплеєм та покращеною камерою.",
        "discount": 250,
        "imagePath": "img/iphone15promax.jpg",
        "reviews": 600
      },
      {
    "model": "Meizu M1 Note",
    "price": 250,
    "brand": "Meizu",
    "os": "Android",
    "color": "blue",
    "description": "Meizu M1 Note - це доступний смартфон з хорошою камерою і яскравим дисплеєм.",
    "discount": 25,
    "imagePath": "img/meizuM1Note.jpg",
    "reviews": 1500
  },
  {
    "model": "Meizu M2 Note",
    "price": 270,
    "brand": "Meizu",
    "os": "Android",
    "color": "white",
    "description": "Meizu M2 Note - це покращена версія M1 Note з оновленими характеристиками.",
    "discount": 27,
    "imagePath": "img/meizuM2Note.jpg",
    "reviews": 1600
  },
  {
    "model": "Meizu M3 Note",
    "price": 300,
    "brand": "Meizu",
    "os": "Android",
    "color": "gray",
    "description": "Meizu M3 Note - це стильний смартфон з металевим корпусом і хорошою камерою.",
    "discount": 30,
    "imagePath": "img/meizuM3Note.jpg",
    "reviews": 1700
  },
  {
    "model": "Meizu M5 Note",
    "price": 320,
    "brand": "Meizu",
    "os": "Android",
    "color": "black",
    "description": "Meizu M5 Note - це бюджетний смартфон з хорошою камерою і великим дисплеєм.",
    "discount": 32,
    "imagePath": "img/meizuM5Note.jpg",
    "reviews": 1800
  },
  {
    "model": "Meizu M6 Note",
    "price": 350,
    "brand": "Meizu",
    "os": "Android",
    "color": "gold",
    "description": "Meizu M6 Note - це смартфон з подвійною камерою і великим акумулятором.",
    "discount": 35,
    "imagePath": "img/meizuM6Note.jpg",
    "reviews": 1900
  },
  {
    "model": "Meizu M3s",
    "price": 200,
    "brand": "Meizu",
    "os": "Android",
    "color": "silver",
    "description": "Meizu M3s - це компактний і доступний смартфон з хорошою камерою.",
    "discount": 20,
    "imagePath": "img/meizuM3s.jpg",
    "reviews": 2000
  },
  {
    "model": "Meizu M5s",
    "price": 220,
    "brand": "Meizu",
    "os": "Android",
    "color": "black",
    "description": "Meizu M5s - це покращена версія M3s з більш потужним процесором.",
    "discount": 22,
    "imagePath": "img/meizuM5s.jpg",
    "reviews": 2100
  },
  {
    "model": "Meizu M6s",
    "price": 240,
    "brand": "Meizu",
    "os": "Android",
    "color": "blue",
    "description": "Meizu M6s - це смартфон з сучасним дизайном і хорошими характеристиками.",
    "discount": 24,
    "imagePath": "img/meizuM6s.jpg",
    "reviews": 2200
  },
  {
    "model": "Meizu MX4",
    "price": 350,
    "brand": "Meizu",
    "os": "Android",
    "color": "gray",
    "description": "Meizu MX4 - це смартфон з чудовою камерою і високою продуктивністю.",
    "discount": 35,
    "imagePath": "img/meizuMX4.jpg",
    "reviews": 2300
  },
  {
    "model": "Meizu MX5",
    "price": 400,
    "brand": "Meizu",
    "os": "Android",
    "color": "black",
    "description": "Meizu MX5 - це флагманський смартфон з металевим корпусом і відмінною камерою.",
    "discount": 40,
    "imagePath": "img/meizuMX5.jpg",
    "reviews": 2400
  },
  {
    "model": "Meizu MX6",
    "price": 450,
    "brand": "Meizu",
    "os": "Android",
    "color": "gold",
    "description": "Meizu MX6 - це стильний смартфон з тонким корпусом і потужним процесором.",
    "discount": 45,
    "imagePath": "img/meizuMX6.jpg",
    "reviews": 2500
  },
  {
    "model": "Meizu Pro 5",
    "price": 500,
    "brand": "Meizu",
    "os": "Android",
    "color": "silver",
    "description": "Meizu Pro 5 - це преміальний смартфон з чудовою камерою і великим дисплеєм.",
    "discount": 50,
    "imagePath": "img/meizuPro5.jpg",
    "reviews": 2600
  },
  {
    "model": "Meizu Pro 6",
    "price": 550,
    "brand": "Meizu",
    "os": "Android",
    "color": "black",
    "description": "Meizu Pro 6 - це оновлена версія Pro 5 з більш потужним процесором.",
    "discount": 55,
    "imagePath": "img/meizuPro6.jpg",
    "reviews": 2700
  },
  {
    "model": "Meizu Pro 7",
    "price": 600,
    "brand": "Meizu",
    "os": "Android",
    "color": "blue",
    "description": "Meizu Pro 7 - це інноваційний смартфон з двома екранами і відмінною камерою.",
    "discount": 60,
    "imagePath": "img/meizuPro7.jpg",
    "reviews": 2800
  },
  {
    "model": "Meizu Pro 7 Plus",
    "price": 650,
    "brand": "Meizu",
    "os": "Android",
    "color": "gold",
    "description": "Meizu Pro 7 Plus - це версія Pro 7 з більшим дисплеєм і покращеними характеристиками.",
    "discount": 65,
    "imagePath": "img/meizuPro7Plus.jpg",
    "reviews": 2900
  },
  {
    "model": "Meizu 16th",
    "price": 700,
    "brand": "Meizu",
    "os": "Android",
    "color": "black",
    "description": "Meizu 16th - це флагманський смартфон з тонкими рамками і високою продуктивністю.",
    "discount": 70,
    "imagePath": "img/meizu16th.jpg",
    "reviews": 3000
  },
  {
    "model": "Meizu 16th Plus",
    "price": 750,
    "brand": "Meizu",
    "os": "Android",
    "color": "blue",
    "description": "Meizu 16th Plus - це версія 16th з більшим екраном і потужним процесором.",
    "discount": 75,
    "imagePath": "img/meizu16thPlus.jpg",
    "reviews": 3100
  },
  {
    "model": "Meizu 16X",
    "price": 650,
    "brand": "Meizu",
    "os": "Android",
    "color": "black",
    "description": "Meizu 16X - це смартфон середнього класу з відмінною камерою і хорошою продуктивністю.",
    "discount": 65,
    "imagePath": "img/meizu16X.jpg",
    "reviews": 3200
  },
  {
    "model": "Meizu 16s",
    "price": 800,
    "brand": "Meizu",
    "os": "Android",
    "color": "gold",
    "description": "Meizu 16s - це флагманський смартфон з чудовою камерою і високою продуктивністю.",
    "discount": 80,
    "imagePath": "img/meizu16s.jpg",
    "reviews": 3300
  },
  {
    "model": "Meizu 16s Pro",
    "price": 850,
    "brand": "Meizu",
    "os": "Android",
    "color": "black",
    "description": "Meizu 16s Pro - це покращена версія 16s з потужним процесором і додатковими функціями.",
    "discount": 85,
    "imagePath": "img/meizu16sPro.jpg",
    "reviews": 3400
  },
  {
    "model": "Meizu 17",
    "price": 900,
    "brand": "Meizu",
    "os": "Android",
    "color": "blue",
    "description": "Meizu 17 - це новий флагман з підтримкою 5G і чудовою камерою.",
    "discount": 90,
    "imagePath": "img/meizu17.jpg",
    "reviews": 3500
  },
  {
    "model": "Meizu 17 Pro",
    "price": 950,
    "brand": "Meizu",
    "os": "Android",
    "color": "black",
    "description": "Meizu 17 Pro - це покращена версія Meizu 17 з преміальними матеріалами і додатковими функціями.",
    "discount": 95,
    "imagePath": "img/meizu17Pro.jpg",
    "reviews": 3600
  },
  {
    "model": "Motorola Moto G4",
    "price": 200,
    "brand": "Motorola",
    "os": "Android",
    "color": "black",
    "description": "Motorola Moto G4 - це доступний смартфон з хорошим екраном і камерою.",
    "discount": 20,
    "imagePath": "img/motorolaMotoG4.jpg",
    "reviews": 1500
  },
  {
    "model": "Motorola Moto G5",
    "price": 250,
    "brand": "Motorola",
    "os": "Android",
    "color": "gray",
    "description": "Motorola Moto G5 - це оновлена версія Moto G4 з покращеною продуктивністю.",
    "discount": 25,
    "imagePath": "img/motorolaMotoG5.jpg",
    "reviews": 1600
  },
  {
    "model": "Motorola Moto G6",
    "price": 300,
    "brand": "Motorola",
    "os": "Android",
    "color": "white",
    "description": "Motorola Moto G6 - це смартфон середнього класу з хорошим екраном і камерою.",
    "discount": 30,
    "imagePath": "img/motorolaMotoG6.jpg",
    "reviews": 1700
  },
  {
    "model": "Motorola Moto G7",
    "price": 350,
    "brand": "Motorola",
    "os": "Android",
    "color": "black",
    "description": "Motorola Moto G7 - це смартфон з великим дисплеєм і хорошою продуктивністю.",
    "discount": 35,
    "imagePath": "img/motorolaMotoG7.jpg",
    "reviews": 1800
  },
  {
    "model": "Motorola Moto G8",
    "price": 400,
    "brand": "Motorola",
    "os": "Android",
    "color": "blue",
    "description": "Motorola Moto G8 - це оновлений смартфон з покращеними характеристиками і камерою.",
    "discount": 40,
    "imagePath": "img/motorolaMotoG8.jpg",
    "reviews": 1900
  },
  {
    "model": "Motorola Moto G9",
    "price": 450,
    "brand": "Motorola",
    "os": "Android",
    "color": "gray",
    "description": "Motorola Moto G9 - це смартфон з чудовою батареєю і хорошою продуктивністю.",
    "discount": 45,
    "imagePath": "img/motorolaMotoG9.jpg",
    "reviews": 2000
  },
  {
    "model": "Motorola Moto G9 Plus",
    "price": 500,
    "brand": "Motorola",
    "os": "Android",
    "color": "gold",
    "description": "Motorola Moto G9 Plus - це версія G9 з великим екраном і покращеною камерою.",
    "discount": 50,
    "imagePath": "img/motorolaMotoG9Plus.jpg",
    "reviews": 2100
  },
  {
    "model": "Motorola Moto G10",
    "price": 550,
    "brand": "Motorola",
    "os": "Android",
    "color": "black",
    "description": "Motorola Moto G10 - це смартфон середнього класу з великим екраном і потужним акумулятором.",
    "discount": 55,
    "imagePath": "img/motorolaMotoG10.jpg",
    "reviews": 2200
  },
  {
    "model": "Motorola Moto G30",
    "price": 600,
    "brand": "Motorola",
    "os": "Android",
    "color": "blue",
    "description": "Motorola Moto G30 - це новий смартфон середнього класу з підтримкою 5G.",
    "discount": 60,
    "imagePath": "img/motorolaMotoG30.jpg",
    "reviews": 2300
  },
  {
    "model": "Motorola Moto G60",
    "price": 650,
    "brand": "Motorola",
    "os": "Android",
    "color": "gold",
    "description": "Motorola Moto G60 - це смартфон з потужною камерою і великим дисплеєм.",
    "discount": 65,
    "imagePath": "img/motorolaMotoG60.jpg",
    "reviews": 2400
  },
  {
    "model": "Motorola Moto G100",
    "price": 700,
    "brand": "Motorola",
    "os": "Android",
    "color": "gray",
    "description": "Motorola Moto G100 - це потужний смартфон з підтримкою 5G і великою батареєю.",
    "discount": 70,
    "imagePath": "img/motorolaMotoG100.jpg",
    "reviews": 2500
  },
  {
    "model": "Motorola Moto G200",
    "price": 750,
    "brand": "Motorola",
    "os": "Android",
    "color": "black",
    "description": "Motorola Moto G200 - це флагманський смартфон з потужним процесором і великою батареєю.",
    "discount": 75,
    "imagePath": "img/motorolaMotoG200.jpg",
    "reviews": 2600
  },
  {
    "model": "Motorola Moto E6",
    "price": 180,
    "brand": "Motorola",
    "os": "Android",
    "color": "blue",
    "description": "Motorola Moto E6 - це бюджетний смартфон з базовими характеристиками і хорошим екраном.",
    "discount": 18,
    "imagePath": "img/motorolaMotoE6.jpg",
    "reviews": 2700
  },
  {
    "model": "Motorola Moto E7",
    "price": 220,
    "brand": "Motorola",
    "os": "Android",
    "color": "black",
    "description": "Motorola Moto E7 - це покращена версія E6 з більшою батареєю і кращою камерою.",
    "discount": 22,
    "imagePath": "img/motorolaMotoE7.jpg",
    "reviews": 2800
  },
  {
    "model": "Motorola Moto E7 Plus",
    "price": 250,
    "brand": "Motorola",
    "os": "Android",
    "color": "gray",
    "description": "Motorola Moto E7 Plus - це версія E7 з потужнішою батареєю і покращеними характеристиками.",
    "discount": 25,
    "imagePath": "img/motorolaMotoE7Plus.jpg",
    "reviews": 2900
  },
  {
    "model": "Motorola Moto E8",
    "price": 270,
    "brand": "Motorola",
    "os": "Android",
    "color": "white",
    "description": "Motorola Moto E8 - це новий бюджетний смартфон з хорошою камерою і великим екраном.",
    "discount": 27,
    "imagePath": "img/motorolaMotoE8.jpg",
    "reviews": 3000
  },
  {
    "model": "Motorola Moto E20",
    "price": 300,
    "brand": "Motorola",
    "os": "Android",
    "color": "black",
    "description": "Motorola Moto E20 - це бюджетний смартфон з великим дисплеєм і хорошою батареєю.",
    "discount": 30,
    "imagePath": "img/motorolaMotoE20.jpg",
    "reviews": 3100
  },
  {
    "model": "Motorola Moto E30",
    "price": 350,
    "brand": "Motorola",
    "os": "Android",
    "color": "blue",
    "description": "Motorola Moto E30 - це покращена версія E20 з потужнішою батареєю і кращою камерою.",
    "discount": 35,
    "imagePath": "img/motorolaMotoE30.jpg",
    "reviews": 3200
  },
  {
    "model": "Motorola Moto E40",
    "price": 400,
    "brand": "Motorola",
    "os": "Android",
    "color": "gold",
    "description": "Motorola Moto E40 - це новий смартфон середнього класу з великим дисплеєм і хорошою камерою.",
    "discount": 40,
    "imagePath": "img/motorolaMotoE40.jpg",
    "reviews": 3300
  },
  {
    "model": "Motorola One Vision",
    "price": 450,
    "brand": "Motorola",
    "os": "Android",
    "color": "gray",
    "description": "Motorola One Vision - це стильний смартфон з подвійною камерою і чистим Android.",
    "discount": 45,
    "imagePath": "img/motorolaOneVision.jpg",
    "reviews": 3400
  }
    ]
module.exports = products;
